"""API Response Recorder — record and sanitize API endpoints as pytest fixtures."""

import argparse
import json
import logging
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

logger = logging.getLogger("api_response_recorder")

DEFAULT_SECRET_KEYS: Set[str] = {
    "token",
    "password",
    "secret",
    "email",
    "key",
    "private_key",
    "passwd",
    "auth",
    "pass",
    "api_key",
    "apikey",
    "session",
}

DEFAULT_SECRET_HEADERS: Set[str] = {
    "authorization",
    "cookie",
    "set-cookie",
    "x-api-key",
    "proxy-authorization",
}


def setup_logging(verbose: bool) -> None:
    """Configure console logging based on verbosity level."""
    level = logging.DEBUG if verbose else logging.INFO
    handler = logging.StreamHandler(sys.stdout)
    formatter = logging.Formatter(
        "%(asctime)s - %(levelname)s - %(message)s", datefmt="%H:%M:%S"
    )
    handler.setFormatter(formatter)
    logger.setLevel(level)
    logger.addHandler(handler)


def sanitize_headers(
    headers: Dict[str, str], custom_headers: Set[str]
) -> Dict[str, str]:
    """Mask sensitive values in HTTP headers."""
    sanitized = {}
    mask_headers = DEFAULT_SECRET_HEADERS.union(custom_headers)
    for k, v in headers.items():
        if k.lower() in mask_headers:
            sanitized[k] = "<MASKED>"
        else:
            sanitized[k] = v
    return sanitized


def sanitize_json_val(val: Any, mask_keys: Set[str], custom_patterns: List[str]) -> Any:
    """Recursively mask sensitive values in JSON dictionaries or lists."""
    if isinstance(val, dict):
        sanitized_dict = {}
        for k, v in val.items():
            if k.lower() in mask_keys:
                sanitized_dict[k] = "<MASKED>"
            else:
                sanitized_dict[k] = sanitize_json_val(v, mask_keys, custom_patterns)
        return sanitized_dict

    if isinstance(val, list):
        return [sanitize_json_val(item, mask_keys, custom_patterns) for item in val]

    if isinstance(val, str):
        # Apply regex custom patterns on string values
        for pat in custom_patterns:
            try:
                val = re.sub(pat, "<MASKED>", val)
            except re.error as e:
                logger.error("Invalid regex pattern '%s': %s", pat, e)
        return val

    return val


def sanitize_body(body: str, mask_keys: Set[str], custom_patterns: List[str]) -> str:
    """Sanitize request/response body payload."""
    if not body:
        return ""

    try:
        # Check if JSON
        parsed = json.loads(body)
        sanitized = sanitize_json_val(parsed, mask_keys, custom_patterns)
        return json.dumps(sanitized, indent=2)
    except ValueError:
        # Fallback to plain text regex replacements
        for pat in custom_patterns:
            try:
                body = re.sub(pat, "<MASKED>", body)
            except re.error as e:
                logger.error("Invalid regex pattern '%s': %s", pat, e)
        return body


def fetch_api(
    url: str,
    method: str,
    headers: Dict[str, str],
    data: Optional[str],
) -> Tuple[int, Dict[str, str], str]:
    """Execute the HTTP request using standard urllib."""
    body_bytes = data.encode("utf-8") if data else None

    # Exclude Content-Length if empty
    if not body_bytes and "Content-Length" in headers:
        headers = {k: v for k, v in headers.items() if k.lower() != "content-length"}

    req = urllib.request.Request(
        url,
        data=body_bytes,
        headers=headers,
        method=method,
    )

    try:
        with urllib.request.urlopen(req, timeout=15) as response:  # nosec B310
            status = response.status
            resp_headers = dict(response.headers.items())
            resp_body = response.read().decode("utf-8")
            return status, resp_headers, resp_body
    except urllib.error.HTTPError as e:
        logger.error("HTTP error received: %d", e.code)
        # Still return details if body exists
        try:
            err_body = e.read().decode("utf-8")
        except OSError:
            err_body = ""
        return e.code, dict(e.headers.items()), err_body
    except Exception as e:  # pylint: disable=broad-exception-caught
        logger.error("Failed to fetch endpoint: %s", e)
        sys.exit(1)


def generate_fixture_loader(
    fixture_json_path: Path, output_py_path: Path, fixture_name: str
) -> None:
    """Write a companion python file housing a pytest mock fixture loader."""
    relative_json_name = fixture_json_path.name
    code = f'''"""Pytest mock fixture loader generated by API Response Recorder."""

from pathlib import Path
from unittest.mock import MagicMock
import urllib.request
import json
import pytest

@pytest.fixture
def mock_{fixture_name}(monkeypatch: pytest.MonkeyPatch) -> MagicMock:
    """Mock urllib.request.urlopen to yield the recorded sanitized API response."""
    fixture_file = Path(__file__).parent / "{relative_json_name}"

    # Read the mock response payload
    with open(fixture_file, "r", encoding="utf-8") as f:
        mock_data = f.read()

    # Mock response object
    mock_response = MagicMock()
    mock_response.status = 200
    mock_response.read.return_value = mock_data.encode("utf-8")

    # Simple JSON-placeholder header mocks
    mock_response.headers = {{"Content-Type": "application/json"}}
    mock_response.__enter__.return_value = mock_response

    # Monkeypatch urlopen
    mock_urlopen = MagicMock(return_value=mock_response)
    monkeypatch.setattr(urllib.request, "urlopen", mock_urlopen)

    return mock_urlopen
'''
    try:
        with open(output_py_path, "w", encoding="utf-8") as f:
            f.write(code)
        logger.info("Generated pytest fixture loader: %s", output_py_path)
    except OSError as e:
        logger.error("Failed to write python fixture loader: %s", e)


def record_endpoint(
    url: str,
    method: str,
    headers: Dict[str, str],
    data: Optional[str],
    output_json_path: Path,
    output_py_path: Optional[Path],
    mask_keys: Set[str],
    mask_headers: Set[str],
    custom_patterns: List[str],
) -> None:
    """Fetch endpoint, sanitize headers/body, and write json + python helper files."""
    # pylint: disable=too-many-arguments,too-many-positional-arguments,too-many-locals
    logger.info("Fetching API response from %s ...", url)
    status, resp_headers, resp_body = fetch_api(url, method, headers, data)
    logger.info("Response Status: %d", status)

    sanitized_headers = sanitize_headers(resp_headers, mask_headers)
    sanitized_body = sanitize_body(resp_body, mask_keys, custom_patterns)

    # Compile archive
    archive = {
        "status": status,
        "headers": sanitized_headers,
        "body": sanitized_body,
    }

    try:
        # Ensure parent directories exist
        output_json_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_json_path, "w", encoding="utf-8") as f:
            # We preserve formatting or write pretty JSON
            f.write(json.dumps(archive, indent=2))
        logger.info("Saved sanitized API response to %s", output_json_path)
    except OSError as e:
        logger.error("Failed to write json fixture: %s", e)
        sys.exit(1)

    if output_py_path:
        # Derive fixture name from filename stem
        fixture_name = re.sub(r"[^a-zA-Z0-9_]", "_", output_json_path.stem)
        output_py_path.parent.mkdir(parents=True, exist_ok=True)
        generate_fixture_loader(output_json_path, output_py_path, fixture_name)


def main() -> None:
    """CLI entry point for API Response Recorder."""
    parser = argparse.ArgumentParser(
        description=(
            "Fetch API responses, sanitize sensitive fields, "
            "and output test fixtures."
        )
    )
    parser.add_argument(
        "url",
        type=str,
        help="Target URL of the API endpoint to record",
    )
    parser.add_argument(
        "--output-json",
        type=str,
        required=True,
        help="Path where the sanitized JSON response details should be saved",
    )
    parser.add_argument(
        "--output-py",
        type=str,
        help="Optional path to output the companion python pytest mock fixture file",
    )
    parser.add_argument(
        "--method",
        type=str,
        default="GET",
        help="HTTP request method (default: GET)",
    )
    parser.add_argument(
        "--header",
        action="append",
        default=[],
        help="HTTP header in format Key:Value (repeatable)",
    )
    parser.add_argument(
        "--data",
        type=str,
        help="Payload string to send with POST/PUT/PATCH requests",
    )
    parser.add_argument(
        "--mask-key",
        action="append",
        default=[],
        help="Additional JSON keys to mask (repeatable)",
    )
    parser.add_argument(
        "--mask-header",
        action="append",
        default=[],
        help="Additional HTTP headers to mask (repeatable)",
    )
    parser.add_argument(
        "--mask-pattern",
        action="append",
        default=[],
        help="Regex pattern to mask inside string body fields (repeatable)",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable detailed log descriptions",
    )

    args = parser.parse_args()
    setup_logging(args.verbose)

    # Parse headers
    req_headers = {}
    for h in args.header:
        if ":" not in h:
            logger.error("Invalid header format: '%s'. Expected Key:Value", h)
            sys.exit(1)
        k, v = h.split(":", 1)
        req_headers[k.strip()] = v.strip()

    output_json = Path(args.output_json)
    output_py = Path(args.output_py) if args.output_py else None

    # Merge custom masks
    mask_keys = DEFAULT_SECRET_KEYS.union(set(k.lower() for k in args.mask_key))
    mask_headers = DEFAULT_SECRET_HEADERS.union(
        set(h.lower() for h in args.mask_header)
    )

    record_endpoint(
        args.url,
        args.method,
        req_headers,
        args.data,
        output_json,
        output_py,
        mask_keys,
        mask_headers,
        args.mask_pattern,
    )


if __name__ == "__main__":
    main()
