"""Generated File Check Tool.

Detects generated artifacts committed to repository that no longer match
their source files, using header annotations, hash checksums, or running
generator commands in temporary environments.
"""

# pylint: disable=too-many-branches,too-many-statements,too-many-locals
# pylint: disable=too-few-public-methods,too-many-return-statements

import argparse
import hashlib
import json
import re
import subprocess  # nosec B404
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

GENERATED_HEADER_PATTERNS = [
    re.compile(r"@generated", re.IGNORECASE),
    re.compile(r"DO NOT EDIT", re.IGNORECASE),
    re.compile(r"AUTO-GENERATED FILE", re.IGNORECASE),
    re.compile(r"Code generated by .* DO NOT EDIT", re.IGNORECASE),
]


@dataclass
class ManifestEntry:
    """Entry defining a source -> generated artifact mapping."""

    source_path: Path
    generated_path: Path
    generator_command: Optional[str] = None
    expected_hash: Optional[str] = None


@dataclass
class CheckResult:
    """Result of checking a generated file."""

    generated_path: Path
    is_generated: bool
    is_in_sync: bool
    status_message: str


def is_file_generated(file_path: Path) -> bool:
    """Check if a file contains auto-generated header annotations."""
    if not file_path.is_file():
        return False

    try:
        content = file_path.read_text(encoding="utf-8", errors="ignore")
        lines = content.splitlines()[:20]
        header = "\n".join(lines)
        return any(pattern.search(header) for pattern in GENERATED_HEADER_PATTERNS)
    except (OSError, UnicodeDecodeError):
        return False


def compute_file_hash(file_path: Path) -> str:
    """Compute SHA-256 hash of a file."""
    if not file_path.exists():
        return ""
    hasher = hashlib.sha256()
    with open(file_path, "rb") as f:
        while chunk := f.read(8192):
            hasher.update(chunk)
    return hasher.hexdigest()


def check_manifest_entry(entry: ManifestEntry, root_dir: Path) -> CheckResult:
    """Verify if a generated file is in sync with its source file/generator."""
    src = root_dir / entry.source_path
    gen = root_dir / entry.generated_path

    if not src.exists():
        return CheckResult(
            gen, True, False, f"Source file missing: {entry.source_path}"
        )

    if not gen.exists():
        return CheckResult(
            gen, True, False, f"Generated file missing: {entry.generated_path}"
        )

    if entry.expected_hash:
        current_hash = compute_file_hash(gen)
        if current_hash != entry.expected_hash:
            msg = (
                f"Hash mismatch! Expected {entry.expected_hash[:8]}, "
                f"got {current_hash[:8]}"
            )
            return CheckResult(gen, True, False, msg)
        return CheckResult(gen, True, True, "In sync (hash match)")

    if entry.generator_command:
        with tempfile.TemporaryDirectory() as tmp_dir:
            tmp_path = Path(tmp_dir)
            tmp_gen = tmp_path / entry.generated_path.name

            cmd = entry.generator_command.format(
                source=str(src.resolve()),
                output=str(tmp_gen.resolve()),
            )

            try:
                proc = subprocess.run(  # nosec B602
                    cmd,
                    shell=True,
                    capture_output=True,
                    text=True,
                    timeout=60,
                    check=False,
                )
                if proc.returncode != 0:
                    err_msg = proc.stderr.strip()
                    return CheckResult(
                        gen,
                        True,
                        False,
                        f"Generator failed with code {proc.returncode}: {err_msg}",
                    )

                if not tmp_gen.exists():
                    return CheckResult(
                        gen,
                        True,
                        False,
                        f"Generator ran but did not output to {tmp_gen.name}",
                    )

                gen_hash = compute_file_hash(gen)
                tmp_hash = compute_file_hash(tmp_gen)

                if gen_hash != tmp_hash:
                    return CheckResult(
                        gen,
                        True,
                        False,
                        "Generated file out of sync with generator output!",
                    )

                return CheckResult(gen, True, True, "In sync (generator rerun match)")
            except Exception as e:  # pylint: disable=broad-exception-caught
                return CheckResult(gen, True, False, f"Generator error: {str(e)}")

    return CheckResult(gen, True, True, "File exists (no generator/hash specified)")


def load_manifest(manifest_path: Path) -> List[ManifestEntry]:
    """Parse manifest file containing generation mappings."""
    if not manifest_path.exists():
        return []

    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    entries = []
    for item in data.get("mappings", []):
        entries.append(
            ManifestEntry(
                source_path=Path(item["source"]),
                generated_path=Path(item["generated"]),
                generator_command=item.get("command"),
                expected_hash=item.get("hash"),
            )
        )
    return entries


def scan_directory_for_generated(root_dir: Path) -> List[Path]:
    """Scan repository files to detect @generated headers."""
    generated_files: List[Path] = []
    for path in root_dir.rglob("*"):
        if path.is_file() and not any(part.startswith(".") for part in path.parts):
            if is_file_generated(path):
                generated_files.append(path)
    return generated_files


def main(args: Optional[List[str]] = None) -> int:
    """CLI entry point for generated-file-check."""
    parser = argparse.ArgumentParser(
        description="Detect out-of-sync generated files in Git repository."
    )
    parser.add_argument(
        "--root",
        default=".",
        help="Root directory of repository (default: current directory).",
    )
    parser.add_argument(
        "--manifest",
        default=".generated-manifest.json",
        help="Path to manifest JSON file (default: .generated-manifest.json).",
    )
    parser.add_argument(
        "--scan-headers",
        action="store_true",
        help="Scan files for @generated annotations.",
    )

    parsed = parser.parse_args(args)
    root_dir = Path(parsed.root).resolve()
    manifest_path = root_dir / parsed.manifest

    results: List[CheckResult] = []
    out_of_sync_count = 0

    if manifest_path.exists():
        print(f"Loading manifest from {manifest_path}...")
        entries = load_manifest(manifest_path)
        for entry in entries:
            res = check_manifest_entry(entry, root_dir)
            results.append(res)
            if not res.is_in_sync:
                out_of_sync_count += 1

    if parsed.scan_headers:
        print("Scanning repository for @generated header annotations...")
        gen_files = scan_directory_for_generated(root_dir)
        for path in gen_files:
            rel_path = path.relative_to(root_dir)
            print(f"Detected generated header: {rel_path}")

    print("\n=== GENERATED FILES CHECK SUMMARY ===")
    if not results:
        print("No manifest mappings checked.")
    else:
        for res in results:
            status = "OK" if res.is_in_sync else "OUT-OF-SYNC"
            print(f"[{status}] {res.generated_path}: {res.status_message}")

    if out_of_sync_count > 0:
        print(f"\nFAILURE: {out_of_sync_count} generated file(s) out of sync!")
        return 1

    print("\nSUCCESS: All generated files are in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
