#!/usr/bin/env python3
"""Command Replay.

Records terminal workflows interactively, replaces dynamic hardcoded values with
reusable script parameters, and exports clean shell scripts.
"""

import argparse
import json
import os
import subprocess  # nosec B404
import sys
from typing import Any, Dict, List


def run_recording(output_file: str) -> None:
    """Interactively execute commands in a loop, recording inputs and exits."""
    print("========================================================================")
    print("COMMAND REPLAY: INTERACTIVE SESSION RECORDER")
    print("========================================================================")
    print("Type your commands below. They will be executed in your local shell.")
    print("Type 'exit' or 'done' to stop recording and write the raw history file.")
    print("-" * 80)

    history: List[Dict[str, Any]] = []
    cwd = os.getcwd()

    while True:
        try:
            cmd = input(f"[{os.path.basename(cwd)}]$ ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\nRecording stopped.")
            break

        if not cmd:
            continue

        if cmd.lower() in ("exit", "done"):
            print("\nSaving raw history...")
            break

        # Handle directory change (mock it so CWD works in subprocesses)
        if cmd.startswith("cd "):
            target = cmd[3:].strip()
            new_dir = os.path.abspath(os.path.join(cwd, target))
            if os.path.exists(new_dir) and os.path.isdir(new_dir):
                cwd = new_dir
                print(f"Changed directory to: {cwd}")
                history.append({"command": cmd, "cwd": cwd})
            else:
                print(f"Error: Directory not found: {target}")
            continue

        # Execute command
        start_cwd = cwd
        try:
            res = subprocess.run(
                cmd, shell=True, cwd=start_cwd, check=False
            )  # nosec B602
            history.append(
                {"command": cmd, "cwd": start_cwd, "exit_code": res.returncode}
            )
        except (OSError, ValueError) as e:
            print(f"Failed to run command: {e}")

    # Write history JSON
    try:
        with open(output_file, "w", encoding="utf-8") as f:
            json.dump(history, f, indent=4)
        print(f"[+] Successfully saved {len(history)} commands to {output_file}")
    except OSError as e:
        print(f"[-] Error writing history file: {e}", file=sys.stderr)


# pylint: disable=too-many-branches,too-many-statements
def run_parameterize(input_file: str, output_script: str) -> None:
    """Load raw recorded history, substitute parameters, and export script."""
    if not os.path.exists(input_file):
        print(f"Error: Recorded file not found: {input_file}", file=sys.stderr)
        return

    try:
        with open(input_file, "r", encoding="utf-8") as f:
            history = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"Error loading recorded history: {e}", file=sys.stderr)
        return

    if not history:
        print("[-] No commands logged in this recording.")
        return

    print("========================================================================")
    print("PARAMETERIZE RECORDED WORKFLOW")
    print("========================================================================")
    print("Enter key-value pairs of strings to replace with parameters.")
    print("Example: Replace '/Users/Name/dev' with '$DEV_DIR'")
    print("Type 'done' or press Enter when finished setting parameters.")
    print("-" * 80)

    replacements = {}
    while True:
        try:
            target = input("String to replace (e.g. '8080'): ").strip()
            if not target:
                break
            param_name = input(
                "Parameter variable name (e.g. '$PORT' or '%PORT%'): "
            ).strip()
            if not param_name:
                break
            replacements[target] = param_name
            print(f"Set replacement rule: '{target}' -> '{param_name}'")
        except (KeyboardInterrupt, EOFError):
            break

    # Build script contents
    lines = []

    # Check output type
    is_powershell = output_script.endswith(".ps1")

    if is_powershell:
        lines.append("#!/usr/bin/env pwsh")
        lines.append("# Reusable workflow script generated by command-replay")
        lines.append("")
        for target, param in replacements.items():
            clean_param = param.replace("$", "").replace("%", "")
            lines.append(f'${clean_param} = "{target}"')
        lines.append("")
    else:
        lines.append("#!/bin/bash")
        lines.append("# Reusable workflow script generated by command-replay")
        lines.append("")
        for target, param in replacements.items():
            clean_param = param.replace("$", "").replace("%", "")
            lines.append(f'{clean_param}="{target}"')
        lines.append("")

    for item in history:
        cmd = item["command"]

        for target, param in replacements.items():
            clean_p = param
            if is_powershell and clean_p.startswith("%") and clean_p.endswith("%"):
                clean_p = "$" + clean_p.replace("%", "")
            elif not is_powershell and clean_p.startswith("$"):
                pass
            cmd = cmd.replace(target, clean_p)

        lines.append(f"# CWD: {item.get('cwd', '.')}")
        lines.append(cmd)
        lines.append("")

    # Write output file
    try:
        with open(output_script, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        print(f"\n[+] Parameterized script written to: {output_script}")
    except OSError as e:
        print(f"[-] Error writing script: {e}", file=sys.stderr)


def main() -> None:
    """CLI Entrypoint."""
    parser = argparse.ArgumentParser(
        description="Record terminal workflows and compile parameterized shell runners."
    )
    subparsers = parser.add_subparsers(dest="command", help="Subcommand to execute.")

    # Record
    rec_parser = subparsers.add_parser(
        "record", help="Start recording terminal commands."
    )
    rec_parser.add_argument(
        "output_json", help="Path to write the raw recorded logs JSON."
    )

    # Parameterize
    param_parser = subparsers.add_parser(
        "parameterize", help="Parameterize and export a recorded session."
    )
    param_parser.add_argument("input_json", help="Path to the raw recorded logs JSON.")
    param_parser.add_argument(
        "output_script", help="Path to write the script (.sh or .ps1)."
    )

    args = parser.parse_args()

    if args.command == "record":
        run_recording(args.output_json)
    elif args.command == "parameterize":
        run_parameterize(args.input_json, args.output_script)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
